### ISSUE TITLE
MaPLE Graph

### ISSUE THREAD

**Issue by Saimic** [muzairkhattak/multimodal-prompt-learning#10]
Hi Uzair Khattak !

I hope you are doing great. I have some queries regarding the Graphs in your paper, (Fig 1- C). I am not able to find the code for these plots in your code. Could you please tell me where can I find the code for same?

**Comment by muzairkhattak** [comment]
Hi @Saimic !

Thank you for your interest in MaPLe. 

We have released a separate jupyter notebook which contains the python code to replicate the radar graph in our paper. 
You can find the notebook at this [link](https://drive.google.com/drive/folders/1usjZqy9BJ878qbeFlZcsqyKFzLyFAo60).

I hope your query is resolved. Kindly let us know in-case there is any other question.

Thank you and kind regards.

**Comment by Saimic** [comment]
Dear @muzairkhattak  thank you for providing the Jupyter Notebook. Could you please also share the code of the Fig3 (t-SNE) and Fig4 (Line Charts) graphs in your paper?

**Comment by JosephKJ** [comment]
> Could you please also share the code of the Fig3 (t-SNE) and Fig4 (Line Charts) graphs in your paper?

+1
