### ISSUE TITLE
Using subsample as new gives really bad acc

### ISSUE THREAD

**Issue by gordonhu608** [muzairkhattak/multimodal-prompt-learning#11]
I noticed that in the reproduce_maple.sh. You used different output directories for base and new but used the same directory for the model path. However, it seems like dassl is looking for the output path for the trained model, if it's not found, then it starts training even when I'm using the same model path. 
So I used the same output dir for new as the base out dir and only change the subclass to "new". However, I can't reproduce the results for "new", receiving very bad acc. I'm sure I didn't change everything else. Why this would happen? Thanks ahead.

**Comment by muzairkhattak** [comment]
Hi @gordonhu608 ,

Thank you for reaching out to us. 

I believe you should keep the output directories separate for both the base and new classes. As both base and new classes utilize the same model, that is why the directory for the model path is same.

You should not change any setting in `reproduce_maple.sh` other than the dataset path value. I also re-verified the steps to reproduce the results and it is working for me. 

Just to re-iterate, you can perform the following steps to reproduce the results.

- Download the MaPLe repository 
- Download the MaPLe weights file for any dataset [(from this link)](https://drive.google.com/drive/folders/1CWuwqBmgSWSbNqT6cijC5rcpNgHIYfcu)
- Add the dataset path in `reproduce_maple.sh`
- Now reproduce the results by running the following command incase for Caltech dataset.
`bash scripts/maple/reproduce_maple.sh caltech101 1 downloaded-dataset-folder-path/`

Running the above steps will produce results for both base and novel classes. Note that you should re-produce the results for all three seeds and then take average to obtain the final results which are reported in the main paper.

I hope this will be helpful.

Kindly let us know incase there is any further confusion or query.

Thank you and kind regards.

**Comment by gordonhu608** [comment]
Thank you so much

**Comment by muzairkhattak** [comment]
No problem!

**Comment by HaoliangZhou** [comment]
Hello! If I want to run reproduce_maple.sh, waht path should be right, "bash scripts/maple/reproduce_maple.sh caltech101 1 MaPLe/output/base2new/train_base/caltech101/shots_16/MaPLe/vit_b16_c2_ep5_batch4_2ctx/seed1/MultiModalPromptLearner" or "MaPLe/output/base2new/train_base/caltech101". 

And why it shows:
  File "train.py", line 245, in <module>
    main(args)
  File "train.py", line 183, in main
    trainer.load_model(args.model_dir, epoch=args.load_epoch)
  File "/home/tjut_haoliangzhou/Documents/Code/MaPLe/trainers/maple.py", line 318, in load_model
    raise FileNotFoundError('Model not found at "{}"'.format(model_path))
FileNotFoundError: Model not found at "/MaPLe/output/base2new/train_base/caltech101//base/seed1/MultiModalPromptLearner/model.pth.tar-5"

Thanks!

**Comment by HaoliangZhou** [comment]
> No problem!

  File "train.py", line 245, in <module>
    main(args)
  File "train.py", line 183, in main
    trainer.load_model(args.model_dir, epoch=args.load_epoch)
  File "/home/tjut_haoliangzhou/Documents/Code/MaPLe/trainers/maple.py", line 318, in load_model
    raise FileNotFoundError('Model not found at "{}"'.format(model_path))
FileNotFoundError: Model not found at "/home/tjut_haoliangzhou/Documents/Code/MaPLe/output/base2new/train_base/caltech101//base/seed1/MultiModalPromptLearner/model.pth.tar-5"
