### ISSUE TITLE
 prints averaged results for base classes

### ISSUE THREAD

**Issue by SHIBOYA** [muzairkhattak/multimodal-prompt-learning#12]
when i run "python parse_test_res.py output/base2new/train_base/imagenet/shots_16/MaPLe/vit_b16_c2_ep5_batch4_2ctx"
got this issue:
AssertionError: Nothing found in output/base2new/train_base/imagenet/shots_16/MaPLe/vit_b16_c2_ep5_batch4_2ctx

and  when i try "python parse_test_res.py output/base2new/test_new/imagenet/shots_16/MaPLe/vit_b16_c2_ep5_batch4_2ctx --test-log"
the results only contain seed2 and seed3, where seed 1?

**Comment by muzairkhattak** [comment]
Hi @SHIBOYA,

Thank you for showing interest in our work. 

> when i run "python parse_test_res.py output/base2new/train_base/imagenet/shots_16/MaPLe/vit_b16_c2_ep5_batch4_2ctx"
got this issue:
AssertionError: Nothing found in output/base2new/train_base/imagenet/shots_16/MaPLe/vit_b16_c2_ep5_batch4_2ctx

For the base-classes, can you try adding the `--test-log` flag in the command as well? 
For example, you could try running:
`python parse_test_res.py output/base2new/train_base/imagenet/shots_16/MaPLe/vit_b16_c2_ep5_batch4_2ctx/ --test-log` 

> and when i try "python parse_test_res.py output/base2new/test_new/imagenet/shots_16/MaPLe/vit_b16_c2_ep5_batch4_2ctx --test-log"

Can you make sure if you have the model trained for seed 1? You can specifically check the seed1 folder and inspect the log files. 

I hope that would be helpful. 

Kindly let me know if you any further queries. 

Thank you.

**Comment by SHIBOYA** [comment]
thank you very much

**Comment by muzairkhattak** [comment]
No problem!
