### ISSUE TITLE
how to compute HM in Table 3?

### ISSUE THREAD

**Issue by SHIBOYA** [muzairkhattak/multimodal-prompt-learning#18]
how to compute HM in Table 3? didn't find any instructions in the run.md

**Comment by muzairkhattak** [comment]
Hi @SHIBOYA,

Kindly refer to the details in this [issue here](https://github.com/muzairkhattak/multimodal-prompt-learning/issues/3#issuecomment-1272903550).

I hope it will resolve your query.

Thank you!

**Comment by muzairkhattak** [comment]
Hi, feel free to re-open the issue in case there is still any confusion.

Thank you!
