### ISSUE TITLE
how to change the epoch of train?

### ISSUE THREAD

**Issue by SHIBOYA** [muzairkhattak/multimodal-prompt-learning#19]
when i  try to change the epoch of the model, i can only find the epoch in the test.sh.  how to change the epoch of train?

**Comment by muzairkhattak** [comment]
Hi @SHIBOYA!

You can change the number of epochs in the config file ([check here) ](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/0d62419f24cb8e65b43adfb0611f1a53620e7214/configs/trainers/MaPLe/vit_b16_c2_ep5_batch4_2ctx.yaml#L18)using the `MAX_EPOCH` argument. 

Thank you!
