### ISSUE TITLE
How many GPUs were used to train the models?

### ISSUE THREAD

**Issue by JosephKJ** [muzairkhattak/multimodal-prompt-learning#2]
Thank you for your amazing works! It would be great if you could comment on the compute requirement for people who are planning to replicate the results. 

- How many GPUs were used?
- On average, how long did the training take?

**Comment by muzairkhattak** [comment]
Hi @JosephKJ, 

Thank you for showing interest in our work! 

Your comments are addressed below:

*  **How many GPUs were used?**
We train MaPLe on each dataset with a batch size of 4 using a single NVIDIA A100 GPU. 

* **On average, how long did the training take?**
Training MaPle on ImageNet for 5 epochs takes 1 hour for a single seed. So results for 3 seeds takes around 3 hours. For all remaining 10 datasets, it combinedly takes around 4 hours (for all 3 seeds) on a single A100 GPU. To ease reproduction of MaPLe results, we have provided [training logs](https://drive.google.com/drive/folders/1EvuvgR8566bL0T7ucvAL3LFVwuUPMRas?usp=sharing) for all datasets.

Please let us know incase there are any other queries.
Thank you.

**Comment by JosephKJ** [comment]
Thank you very much for your swift response. Really appreciate your clarification.
