### ISSUE TITLE
assert len(data_loader) > 0

### ISSUE THREAD

**Issue by Pefect96** [muzairkhattak/multimodal-prompt-learning#23]
Thank you for your work. I am very intrested in this work,  but I meet this kind of error when running the "bash scripts/maple/base2new_train_maple.sh imagenet 1" on Imagenet dataset.  How to solve it?  I have normalized the imagenet  dataset format according to datasets.md. Specially, the imagenet/images/train includes 1000 folds, and the imagenet/images/val alse includes 1000 folds after our classification. 

Traceback (most recent call last):
  File "train.py", line 234, in <module>
    main(args)
  File "train.py", line 169, in main
    trainer = build_trainer(cfg)
  File "/home/abc/dev/abc/Dassl.pytorch/dassl/engine/build.py", line 11, in build_trainer
    return TRAINER_REGISTRY.get(cfg.TRAINER.NAME)(cfg)
  File "/home/abc/dev/abc/Dassl.pytorch/dassl/engine/trainer.py", line 324, in __init__
    self.build_data_loader()
  File "/home/abc/dev/abc/Dassl.pytorch/dassl/engine/trainer.py", line 347, in build_data_loader
    dm = DataManager(self.cfg)
  File "/home/abc/dev/abc/Dassl.pytorch/dassl/data/data_manager.py", line 131, in __init__
    test_loader = build_data_loader(
  File "/home/abc/dev/abc/Dassl.pytorch/dassl/data/data_manager.py", line 48, in build_data_loader
    assert len(data_loader) > 0
AssertionError

**Comment by muzairkhattak** [comment]
Hi @Pefect96,

Thank you for showing interest in our work! 

From the above logs, it looks like the issue is occurring during the creation of test data loader.  

Can you please verify the following checks:

- Your imageNet folder should be organized with a directory structure as follows:

```
imagenet/
|–– images/
|   |–– train/ # contains 1,000 folders like n01440764, n01443537, etc.
|   |–– val/
```

- Also, please verify if you are providing correct data root path in the script file. 
You should provide the parent directory path in which your ImageNet folder is present. The data path should be provided in this [DATA](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/ce9c749dd3bdadeb8c92a852c96ee51e65d4cf5e/scripts/maple/xd_train_maple.sh#L6) variable in the script file. 

Please let us know if your query is resolved. 


Thank you and kind regards.

**Comment by Pefect96** [comment]
> Hi @Pefect96,
> 
> Thank you for showing interest in our work!
> 
> From the above logs, it looks like the issue is occurring during the creation of test data loader.
> 
> Can you please verify the following checks:
> 
> * Your imageNet folder should be organized with a directory structure as follows:
> 
> ```
> imagenet/
> |–– images/
> |   |–– train/ # contains 1,000 folders like n01440764, n01443537, etc.
> |   |–– val/
> ```
> 
> * Also, please verify if you are providing correct data root path in the script file.
>   You should provide the parent directory path in which your ImageNet folder is present. The data path should be provided in this [DATA](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/ce9c749dd3bdadeb8c92a852c96ee51e65d4cf5e/scripts/maple/xd_train_maple.sh#L6) variable in the script file.
> 
> Please let us know if your query is resolved.
> 
> Thank you and kind regards.

Thanks for your reply. My train and val folders are organized as follows: /home/abc/dev/datasets/common/imagenet/images/train, /home/abc/dev/datasets/common/imagenet/images/val, and there are 1000 folders in both train and val folders. Thus, I think there is no error about our folders.
Also, I have provided correct data root path  in this [DATA](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/ce9c749dd3bdadeb8c92a852c96ee51e65d4cf5e/scripts/maple/xd_train_maple.sh#L6) variable in the script file, i.e.,  /home/abc/dev/datasets/common. I do not known where is my error.

**Comment by muzairkhattak** [comment]
Hi @Pefect96,

Can you check if there are images present inside the val folder?

**Comment by Pefect96** [comment]
Thanks, the error is solved. The reason is that I didn't categorize the files in val at the beginning, so the saved preprocessed.pkl file was wrong, and the subsequent training directly read the previously saved preprocessed.pkl. Now I've removed preprocessed.pkl, run it again, and the problem is solved. 

Thank you very much for your reply!
