### ISSUE TITLE
About the Network

### ISSUE THREAD

**Issue by wr-1999** [muzairkhattak/multimodal-prompt-learning#24]
Would it be feasible to replace the network with ResNet

**Comment by muzairkhattak** [comment]
Hi @wr-1999,

Thank you for your message. 

Currently, our MaPLe architecture is explicitly tailored to adapt **Transformers based Vision-Language (V-L) models**. In our project, we did not explore using MaPLe for ResNet type V-L models. 

However, there are some ways to adapt ResNet like architectures with learnable prompts. For example, you can train a grid-like learnable prompt frame over the image in ResNets. 

You can see the following related papers which has explored prompt learning on ResNet like architectures. They can be modified  and extended with a MaPLe design.

1. Visual Prompt Tuning[ (paper link)](https://arxiv.org/abs/2203.12119)
2. Exploring Visual Prompts for Adapting Large-Scale Models [(paper link)](https://arxiv.org/abs/2203.17274)


Kindly let us know if you have any further queries.

Thank you and kind regards.

**Comment by muzairkhattak** [comment]
I am closing the issue. Please feel free to open in-case there are any additional queries.


Thank you.
