### ISSUE TITLE
How to calculate the computational complexity?

### ISSUE THREAD

**Issue by EdmunddzzZ** [muzairkhattak/multimodal-prompt-learning#27]
I saw that there is a Table 8:Comparison of computational complexity among different prompting methods in the paper.

I want to know how to calculate it and if there is any code in it.

Thank you!

**Comment by muzairkhattak** [comment]
Hi @EdmunddzzZ,

Thank you for your interest in MaPLe!

For the FLOPs calculation, we evaluated all methods using [fvcore python library](https://github.com/facebookresearch/fvcore/blob/main/docs/flop_count.md). 

You can calculate the FLOPs with simple commands such as follows. You might need to slightly change the parameters given to the  [forward function of MaPLe](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/ce9c749dd3bdadeb8c92a852c96ee51e65d4cf5e/trainers/maple.py#LL189C42-L189C42), so it can use single input which is a requirement by fvcore package.

```
from fvcore.nn import FlopCountAnalysis
flops = FlopCountAnalysis(model, input) # input is the image
flops.total()  # running this line will print the FLOPs
```
We calculated the FLOPs using Caltech-101 datasets with 1 batch-size for the images.


Furthermore, the throughput was calculated by noting the imagenet inference time taken by each method on a single A100 GPU.

I hope this answers your issue, please let us know incase there are any further queries.

Thank you!

**Comment by EdmunddzzZ** [comment]
@muzairkhattak 
Thank you for your patient explanation！

I also want to know how to draw fig3 t-SNE plots , as I have been following your work and writing a paper recently.

Thank you!

**Comment by muzairkhattak** [comment]
Hi @EdmunddzzZ,

Please refer [to this code](https://github.com/shivanichander/tSNE) which we used to generate the t-SNE plots. You would also need to first generate and store the CLIP vision-encoder image-embeddings. Afterwards, the t-SNE plot code will produce the require plots.

Thank you!

**Comment by jetwu-create** [comment]
Can you provide your code about fig3 ?
