### ISSUE TITLE
 Have you submitted your paper to a journal？

### ISSUE THREAD

**Issue by EdmunddzzZ** [muzairkhattak/multimodal-prompt-learning#29]
Hi @muzairkhattak :
    I want to ask if you submit MaPLe to a journal in that I found there is few paper for prompting  was acccepted . For journal like TPAMI and TIP, there is None.
   Thank you!

**Comment by muzairkhattak** [comment]
Hi @EdmunddzzZ, 

Thank you for your message. I apologize for the delayed response. 

Regarding your query, we have not submitted this work to any journal.
Thank you!
