### ISSUE TITLE
How to compute the harmonic mean

### ISSUE THREAD

**Issue by jingzhengli** [muzairkhattak/multimodal-prompt-learning#3]
Thanhs for sharing the code. After I obtain the results of base classes and novel classes, how to compute the **harmonic mean**?

**Comment by hanoonaR** [comment]
Hi @jingzhengli, 

Thanks for showing interest in our work. 

The harmonic mean is calculated as, $(2 \times Base_{acc} \times Novel_{acc}) / (Base_{acc} + Novel_{acc})$

Thank you.

**Comment by dneirfi** [comment]
Hi, Thanks for sharing the nice work! @jingzhengli @hanoonaR 

I have a question about calculating the harmonic mean.

Base_acc and Nov_acc are the best accuracy in three runs or average in three runs?

Thank you.

**Comment by hanoonaR** [comment]
Hi @dneirfi ,

Please note that we report the *average* over three runs both in Base_acc and Novel_acc, following the general few-shot experimental settings. Hope it is clear. Thank you.
