### ISSUE TITLE
The results of the 11 datasets of CoOp^{\dag} in Table 2.

### ISSUE THREAD

**Issue by JimZAI** [muzairkhattak/multimodal-prompt-learning#31]
Hi, 

Can you provide the results of the 11 datasets of CoOp^{\dag} in Table 2.  There are only average results (i.e., 80.85 | 70.02 | 75.04).

Thank you very much.

**Comment by muzairkhattak** [comment]
Hi @JimZAI,

Thank you for showing interest in our work!

We have uploaded the results in the google sheet provided [at this link.](https://docs.google.com/spreadsheets/d/1Y4699i9QrK9bPpYe-ve6zRr1xKb5pQ9IytL4Fpo6KRo/edit?usp=sharing). You can find the per-dataset results here.

I hope your query is resolved.

Thank you and kind regards!

**Comment by JimZAI** [comment]
Thank you very much.
