### ISSUE TITLE
How is the final model selected

### ISSUE THREAD

**Issue by TicTacToePP** [muzairkhattak/multimodal-prompt-learning#33]
Hi, I wonder how is the final model selected. Is it the final model at the last epoch used directly or we need to select the best model based on the validation set? Thanks.

**Comment by muzairkhattak** [comment]
Hi @TicTacToePP,

Thank you for showing interest in MaPLe!

Regarding your query, the final model obtained at the last epoch is directly used. So there is no model selection based on the validation set.

Thank you and kind regards!

**Comment by TicTacToePP** [comment]
Noted, thanks!
