### ISSUE TITLE
Some errors when I run the code

### ISSUE THREAD

**Issue by bf-yang** [muzairkhattak/multimodal-prompt-learning#36]
Thanks for your great job.

When I run the following code:
bash scripts/vpt/base2new_train_vpt.sh oxford_flowers 1
bash scripts/maple/base2new_train_maple.sh oxford_flowers 1
They both report errors. But when I run the code: bash scripts/coop/main.sh oxford_flowers vit_b16 middle 16 1 False, it works.

It seems that I can only successfully run zeroshotCLIP and CoOp codes. But for VPT and MaPLe codes, it reports an error.

Specifically, when I run bash scripts/vpt/base2new_train_vpt.sh oxford_flowers 1, it reports:

![image](https://github.com/muzairkhattak/multimodal-prompt-learning/assets/82997910/cd199268-2f27-4fc9-9ed0-6393ed000853)

when I run bash scripts/maple/base2new_train_maple.sh oxford_flowers 1, it reports:
![image](https://github.com/muzairkhattak/multimodal-prompt-learning/assets/82997910/90b193ea-7db2-4f90-ad50-3ea2ecb2b65c)

How can I successfully run these two .sh files?

**Comment by muzairkhattak** [comment]
Hi @bf-yang,

Thank you for showing interest in MaPLe!

I think the error caused is due to the use of multiple GPUs. You may need to use only one GPU per training.

So, you can mention the usage of one GPU while running the bash scripts (by using CUDA_VISIBLE_DEVICES=0)

Please let me know if this resolves your issue.

Thank you and kind regards!

**Comment by bf-yang** [comment]
I add  CUDA_VISIBLE_DEVICES=0  into the script file, like:
![image](https://github.com/muzairkhattak/multimodal-prompt-learning/assets/82997910/d4af0b32-0d59-4795-ac9d-5ae17b643bf2)
But it still reports the same error:
![image](https://github.com/muzairkhattak/multimodal-prompt-learning/assets/82997910/a7c14c90-1923-4626-928a-587d33567c2d)

**Comment by muzairkhattak** [comment]
Can you try using this variable like the following:

`CUDA_VISIBLE_DEVICES=0  bash scripts/vpt/base2new_train_vpt.sh oxford_flowers 1`

**Comment by bf-yang** [comment]
It helps me a lot. Thanks very much for your excellent work and your help!
