### ISSUE TITLE
RuntimeError: grad can be implicitly created only for scalar outputs

### ISSUE THREAD

**Issue by fenglincong** [muzairkhattak/multimodal-prompt-learning#37]
Hi, can you help me solve it?

**Comment by muzairkhattak** [comment]
Hi @fenglincong,

Thank you for reaching out to us!

This error is most likely appearing due to the use of multiple GPUs for training. Can you kindly look into the [issue#36](https://github.com/muzairkhattak/multimodal-prompt-learning/issues/36), which has a fix for your issue?

Thank you!

**Comment by fenglincong** [comment]
Okay, thank you.
