### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by nikifori** [muzairkhattak/multimodal-prompt-learning#40]
Do you provide the pretrained models and a demo on how to use them?
Will the models be incorporated into huggingface?

**Comment by muzairkhattak** [comment]
Hi @nikifori,

Thank you for showing interest in MaPLe!

We have provided pre-trained models and evaluation scripts to reproduce our results. Please refer to [RUN.md](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/main/docs/RUN.md) for further details.

Regarding you second query, currently we do not have plans to incorporate MaPLe weights into huggingface. 

Thank you and kind regards!

Sincerely,
Muhammad Uzair
