### ISSUE TITLE
Can MaPLe be a video learner?

### ISSUE THREAD

**Issue by JiangjiangLan** [muzairkhattak/multimodal-prompt-learning#42]
Hi, @muzairkhattak 
First of all, thank you for making breakthrough progress in multimodal prompt learning. 
I am currently working on downstream task video recognition tasks based on multimodal prompts. I am wondering if MaPle can be used as a video learner.

**Comment by muzairkhattak** [comment]
Hi @JiangjiangLan,

Thank you for showing interest in MaPLe. 

Regarding your query, we have not experimented with adopting MaPLe for video tasks, but It could be adapted to videos. You can additionally check papers that have cited MaPLe and see if there is any video-related paper. 

Thank you!
