### ISSUE TITLE
Build a model

### ISSUE THREAD

**Issue by liuchenxin666** [muzairkhattak/multimodal-prompt-learning#45]
Hi, thank you for your excellent work.

Since I'm not very familiar with dassl.pytorch, can I create the model simply and directly?
Similar `model = build_model();`，so that I can get started faster.
At the same time, I also want to make some changes to the model. Can you give me some guidance?

Thank you.

**Comment by muzairkhattak** [comment]
Hi @liuchenxin666,

Thank you for showing interest in MaPLe!

If you only want to create a model, you can proceed like the following:

1. You can create the MaPLe trainer class object by [executing this line.](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/69bce21ae8eda80ad6187534b2dce09cf6c59e17/train.py#L169C33-L169C33)
2. Next you can create your model by running 
`trainer.build_model()`
3. Lastly you can retrieve your MaPLe model as `model = trainer.model`

Regarding your second query, you can make changes to the model in the maple model class which is given in `maple.py` [at this location.](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/main/trainers/maple.py#L180)

Additionally, maple.py relies on CLIP model architecture which is modified accordingly in `model.py` [at this link.](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/main/clip/model.py)

I hope this will be helpful!

Thank you and kind regards!
