### ISSUE TITLE
Download Image-Net

### ISSUE THREAD

**Issue by ChushanZhang** [muzairkhattak/multimodal-prompt-learning#48]
Thanks for your amazing work!

There is a quick question that which dataset you are using for the Image-Net?

Since there are many download options on the offical website, could you kindly guide me?

![Screenshot from 2024-02-19 16-05-17](https://github.com/muzairkhattak/multimodal-prompt-learning/assets/36417130/89ecd254-53ca-4afe-aa0f-a8c88198287a)

**Comment by muzairkhattak** [comment]
Hi @PoopBear1,
Thank you for showing interest in MaPLe!

Regarding your query, kindly note that we use the ImageNet 2012 version dataset in our experiments. You can download them at this link: https://image-net.org/challenges/LSVRC/2012/2012-downloads.php. 

For training images, download:  "Training images (Task 1 & 2)" and for test images, download the file: "Validation images (all tasks)" as shown below.

![image](https://github.com/muzairkhattak/multimodal-prompt-learning/assets/61704085/100edc6d-143c-4d25-ba1f-f17afc6003aa)

Let us know if you have any further queries!

**Comment by ChushanZhang** [comment]
Thank you very much for your prompt reply!

There is also a minor issue with downloading: the Stanford Cars dataset links are all broken. Is it possible to find it somewhere else?

**Comment by muzairkhattak** [comment]
No problem! 

Regarding the Stanford Cars link issue, you can download the complete dataset from Google Drive [using this link.](https://mbzuaiac-my.sharepoint.com/:f:/g/personal/jameel_hassan_mbzuai_ac_ae/EgekN_WCgVRFqnE0X8fXjeEBLzOn5sKTc7cqjMMNZ1CVuw?e=JPs9Rj)

**Comment by ChushanZhang** [comment]
Thank you again, it helps a lot!
