### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by Velpro-collab** [muzairkhattak/multimodal-prompt-learning#52]
作者，你好，你们上传的代码是不是不完整？
from dassl.utils import setup_logger, set_random_seed, collect_env_info
from dassl.config import get_cfg_default
from dassl.engine import build_trainer

**Comment by muzairkhattak** [comment]
I think you have asked the same question in our PromptSRC repository.

Kindly refer to the corresponding issue present [at this link.](https://github.com/muzairkhattak/PromptSRC/issues/9)

Thank you and kind regards!
