### ISSUE TITLE
There's no 'design_details' in build_model()

### ISSUE THREAD

**Issue by zmj2** [muzairkhattak/multimodal-prompt-learning#55]
What should I put in here?

**Comment by muzairkhattak** [comment]
Hi @zmj2,

Thank you for showing interest in MaPLe!

Regarding your query, can you check if you are using the [CLIP code files present](https://github.com/muzairkhattak/multimodal-prompt-learning/tree/main/clip) in our repo? It seems like the `design_details` parameter is present in the `build_model()` function [as shown in these lines.](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/69bce21ae8eda80ad6187534b2dce09cf6c59e17/clip/model.py#L654)

Kind regards!
