### ISSUE TITLE
T-sne plot

### ISSUE THREAD

**Issue by jzw-j** [muzairkhattak/multimodal-prompt-learning#56]
Hello,your fig.3 is very clear,can you provide source code of T-sne plot?

**Comment by muzairkhattak** [comment]
Hi @jzw-j,

Thank you for showing interest in MaPLe!

For plotting the t-SNE embeddings, you can refer [to this issue which](https://github.com/muzairkhattak/ViFi-CLIP/issues/12#issuecomment-1807054414) describes the steps in detail.

Kind regards!

**Comment by muzairkhattak** [comment]
Hi @jzw-j,

I hope your query is resolved regarding the t-SNE plots. Feel free to re-open the issue if you still have any queries.

Thank you!
