### ISSUE TITLE
Data set failure

### ISSUE THREAD

**Issue by dana-niu** [muzairkhattak/multimodal-prompt-learning#58]
Hello,

Create a folder named stanford_cars/ under $DATA.
Download the train images http://ai.stanford.edu/~jkrause/car196/cars_train.tgz.
Download the test images http://ai.stanford.edu/~jkrause/car196/cars_test.tgz.
Download the train labels https://ai.stanford.edu/~jkrause/cars/car_devkit.tgz.
Download the test labels http://ai.stanford.edu/~jkrause/car196/cars_test_annos_withlabels.mat.

This data set can't be linked.
Can you send me a copy of these four parts of data?
Thank you for intruding.

**Comment by muzairkhattak** [comment]
Hi,

Download the complete dataset directly [from this link](https://mbzuaiac-my.sharepoint.com/:f:/g/personal/jameel_hassan_mbzuai_ac_ae/EgekN_WCgVRFqnE0X8fXjeEBLzOn5sKTc7cqjMMNZ1CVuw?e=JPs9Rj) incase there are any issues in downloading from above links.

Thank you!

**Comment by dana-niu** [comment]
Thank you very much for taking the time to reply.      
Thank you！



---- Replied Message ----
| From | Muhammad Uzair ***@***.***> |
| Date | 04/08/2024 20:58 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [muzairkhattak/multimodal-prompt-learning] Data set failure (Issue #58) |

Hi,

Download the complete dataset directly from this link incase there are any issues in downloading from above links.

Thank you!
