### ISSUE TITLE
Can I ask how did you draw this spider chart? 

### ISSUE THREAD

**Issue by ChushanZhang** [muzairkhattak/multimodal-prompt-learning#60]
Dear Authors,

Thank you again for this novel ideas!

I am citing your work in a submission to a conference. However, I am unable to reproduce the spider chart from your paper. Could you kindly inform me about the tool/library you used or explain how you created it?

Appreciaed.

**Comment by muzairkhattak** [comment]
Hi @PoopBear1,

You can find the relevant code [at this link. ](https://github.com/muzairkhattak/multimodal-prompt-learning/issues/10#issuecomment-1436489789)

 Thank you!
