### ISSUE TITLE
您好，我想把vpt的深度改的浅一点，但是总是有如下错误

### ISSUE THREAD

**Issue by Fanfan397** [muzairkhattak/multimodal-prompt-learning#61]
我想改成八层，但是总是这样报错
<img width="1006" alt="截屏2024-04-16 10 00 08" src="https://github.com/muzairkhattak/multimodal-prompt-learning/assets/147038024/7ff59b06-9e27-4fd5-b193-f751545962a2">

**Comment by muzairkhattak** [comment]
Hi @Fanfan397,

From the screen shot, It looks like you are changing the model configuration but also loading the trained model weights that has different model configuration. 

The logs shows: "Loading checkpoint from "output/base2new/.............."

You should not load any model weights if you are training a model.

**Comment by muzairkhattak** [comment]
Hi @Fanfan397,

Can you kindly clarify if your issue is resolved? I am closing the issue for now.

Feel free to open it incase there are any further issues.

Thank you and kind regards!

**Comment by Fanfan397** [comment]
> 你好@Fanfan397，
> 
> 您能否说明一下您的问题是否已解决？我现在要关闭这个问题了。
> 
> 如果还有任何其他问题，请随时打开它。
> 
> 谢谢您，并致以亲切的问候！

我修改好了谢谢您！
