### ISSUE TITLE
where the coupling function code is implemented？

### ISSUE THREAD

**Issue by dana-niu** [muzairkhattak/multimodal-prompt-learning#62]
Hello, can you tell me where the coupling function code is implemented?
Thank you very much.

**Comment by muzairkhattak** [comment]
Hi @dana-niu,

The initialization of coupling function is written [at these lines.](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/69bce21ae8eda80ad6187534b2dce09cf6c59e17/trainers/maple.py#L116)

The usage of coupling function in the forward pass is written [here. ](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/69bce21ae8eda80ad6187534b2dce09cf6c59e17/trainers/maple.py#L172)

Thank you!

**Comment by dana-niu** [comment]
I found it.
Thank you very much for your reply!



---- Replied Message ----
| From | Muhammad Uzair ***@***.***> |
| Date | 04/22/2024 13:13 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [muzairkhattak/multimodal-prompt-learning] where the coupling function code is implemented？ (Issue #62) |

Hi @dana-niu,

The initialization of coupling function is written at these lines.

The usage of coupling function in the forward pass is written here.

Thank you!
