### ISSUE TITLE
Setting of the n_ctx value

### ISSUE THREAD

**Issue by dana-niu** [muzairkhattak/multimodal-prompt-learning#63]
Hello! 
Can you tell me something about the value n_ctx? 
Does his size make a big difference to the results of the experiment?
 Can he set it to 1?
 I really hope to hear from you. Thank you!

**Comment by muzairkhattak** [comment]
Hi @dana-niu,

The variable n_ctx denotes the number of prompt vectors that will be learned during the training process. You can also set it to 1, in which case there will be a single learnable vector at each layer.

Increasing the number of learnable prompt vectors usually increases the learning capacity of the model. However, this could also lead to overfitting on the training dataset.

In summary, increasing n_ctx is recommended only in a supervised setting, while it should be lowered if one is performing generalization experiments, such as base-to-novel or domain generalization.

**Comment by dana-niu** [comment]
Thank you very much for your detailed explanation.
