### ISSUE TITLE
Setting of MAX_EPOCH

### ISSUE THREAD

**Issue by dana-niu** [muzairkhattak/multimodal-prompt-learning#65]
Hello!
I noticed that your MAX_EPOCH: is set to 5 and 2 respectively.
I want to ask you, does this figure mean that your experimental effect is the best under such conditions? Or is it to compare with Co-CoOp data?

**Comment by muzairkhattak** [comment]
Hi @dana-niu,

Thank you for your message. Regarding your query, we use different epochs for training as they are more suited for a separate architecture like MaPLe.

It is not set in a way, to compare with Co-CoOp method or data. 

I hope this is helpful!

Thank you and kind regards!

**Comment by dana-niu** [comment]
Thank you very much for your patient reply.



---- Replied Message ----
| From | Muhammad Uzair ***@***.***> |
| Date | 05/09/2024 18:00 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [muzairkhattak/multimodal-prompt-learning] Setting of MAX_EPOCH (Issue #65) |

Hi @dana-niu,

Thank you for your message. Regarding your query, we use different epochs for training as they are more suited for a separate architecture like MaPLe.

It is not set in a way, to compare with Co-CoOp method or data.

I hope this is helpful!

Thank you and kind regards!

**Comment by dana-niu** [comment]
Hello, I have another question.
Can you tell me how to get the data characteristics and labels of drawing t-SNE diagram?
I would appreciate it if I could receive your reply.

**Comment by muzairkhattak** [comment]
Hi @dana-niu,

Sorry for the delayed response. Can you clarify your question a bit regarding the meaning of data characteristics and labels. 

Thank you!

**Comment by muzairkhattak** [comment]
Hi @dana-niu,

I am closing the issue now. Feel free to reopen it if there are still any queries.

Thank you!
