### ISSUE TITLE
Use of ImageNet

### ISSUE THREAD

**Issue by dana-niu** [muzairkhattak/multimodal-prompt-learning#66]
Hello!
I want to ask.
After I download ImageNet2012, train/contains 1,000 folders like N01440764, N01443537, etc. Do I need any other processing? Or just decompress it all and use it directly?

**Comment by dana-niu** [comment]
Excuse me again, I have another question.
The download link of ImageNetV2 data set cannot be accessed.
Could you please share this data set?
Thank you very much.

**Comment by muzairkhattak** [comment]
Hi @dana-niu,

You need to have the imagenet folder as shown in the following format:

```
imagenet/
|–– images/
|   |–– train/ # contains 1,000 folders like n01440764, n01443537, etc.
|   |–– val/```


So I think your train folder looks great and it should work fine.

**Comment by dana-niu** [comment]
I see. Thank you very much for your reply.



---- Replied Message ----
| From | Muhammad Uzair ***@***.***> |
| Date | 05/09/2024 17:58 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [muzairkhattak/multimodal-prompt-learning] Use of ImageNet (Issue #66) |

Hi @dana-niu,

You need to have the imagenet folder as shown in the following format:

imagenet/
|–– images/
|   |–– train/ # contains 1,000 folders like n01440764, n01443537, etc.
|   |–– val/```


So I think your train folder looks great and it should work fine.
