### ISSUE TITLE
The problem of multi GPU training

### ISSUE THREAD

**Issue by yjn8** [muzairkhattak/multimodal-prompt-learning#68]
Hello!

I have a question to consult. You mentioned using a single NVIDIA A100 GPU for training, but the code seems to support multi GPU training. There may be issues when using multi GPU training, and the main issue may be using nn.DataParallel() for multi GPU parallel training, when using nn.ParameterList() to construct a parameter list simultaneously, there will be an empty error in the forward phase
. The specific error is shown in the following figure. Looking forward to your reply and answers.
![0屏幕截图](https://github.com/muzairkhattak/multimodal-prompt-learning/assets/161722834/b1c99021-2769-46b0-b841-59c65aa06813)
![1屏幕截图](https://github.com/muzairkhattak/multimodal-prompt-learning/assets/161722834/2ba9d130-f2df-4479-bf4d-d788ecba0ac9)

**Comment by muzairkhattak** [comment]
Hi @yjn8,

Thank you for showing interest in MaPLe!

Regarding your question, 

We note that our repository currently do not support the training of MaPLe on multiple GPUs and one might face unexpected errors while using the repo for multiple GPUs.
We will strongly recommend you to proceed with the single GPU training while using our repository. 

Thank you and kind regards!

Sincerely,
Muhammad Uzair

**Comment by muzairkhattak** [comment]
Hi @yjn8,

I am closing the issue now. 
Feel free to open it if there are still any questions!
