### ISSUE TITLE
Where is the innovation point

### ISSUE THREAD

**Issue by zbb1111** [muzairkhattak/multimodal-prompt-learning#70]
Thank you very much for your excellent article. I would like to ask about the modification and innovation of clip, specifically in which position in the code. As a beginner, I really hope to receive your help! Looking forward to your reply, thank you!

**Comment by muzairkhattak** [comment]
Hi @zbb1111,

Thank you for showing interest in MaPLe! 

Regarding your query, please note that our MaPLe framework has been implemented in the following parts of the code:

1) MaPLe trainer: [maple.py](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/main/trainers/maple.py)
2) Vision-Language deep prompting: [clip/model.py](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/main/clip/model.py)

You can checkout these code files for the main implementation of MaPLe framework. 
Let us know if there are any further questions. 
Thank you and kind regards!

**Comment by muzairkhattak** [comment]
Hi @zbb1111,

I am closing the issue now.
Feel free to open it if there are still any issues.
