### ISSUE TITLE
Prompts layer

### ISSUE THREAD

**Issue by nwlxcdh255** [muzairkhattak/multimodal-prompt-learning#72]
Hi, your paper says there are prompts in the front L layer
But I see your code should not be layer 1 is there no prompt
Which means there's an L-1 prompts?
Looking forward to your reply

if not self.first_layer:
if len(compound_prompts_deeper) > 0:
# This means that deeper compound prompts are turned on
# Here it behaves differently for text and visual side
# Forward function is same for both

if not self.text_layer:
# First check if the ith layer needs compound prompts or not
if not (counter > len(compound_prompts_deeper) - 1):

**Comment by muzairkhattak** [comment]
Hi @nwlxcdh255,

Thank you for showing interest in MaPLe!

Regarding your question, kindly note that we are using prompts in the first L layers. 

Actually, in the MaPLe trainer code, we have already used prompts for the first layer (as shown in these lines at [maple.py](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/main/trainers/maple.py) at this [line](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/69bce21ae8eda80ad6187534b2dce09cf6c59e17/trainers/maple.py#L105)). 

Therefore, we do not use additional prompts in the first layer when we are inside [model.py](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/69bce21ae8eda80ad6187534b2dce09cf6c59e17/clip/model.py#L293) (that is why we have the `if not self.first_layer:`). 

So overall we are using learnable prompts in the first L layers. 

I hope that is clear now. Let us know if there are any questions. 

Thank you and kind regards!

**Comment by dana-niu** [comment]
Thank you very much for your reply.
