### ISSUE TITLE
Where V-L coupling function?

### ISSUE THREAD

**Issue by Sandy-program** [muzairkhattak/multimodal-prompt-learning#75]
Hi author, your work is excellent and I am very interested in your work. However, I have a question. As mentioned in your article, the first 8 layers of text prompts can provide visual prompts to the visual encoder through a V-L coupling function, but I have not found the corresponding implementation code for this place. Can you provide the corresponding code location for me? I am very grateful for that.

**Comment by muzairkhattak** [comment]
Hi @Sandy-program,

Thank you for showing interest in MaPLe!

Regarding your query, the corresponding code for the deep prompting at text side can be found [at these lines.](https://github.com/muzairkhattak/multimodal-prompt-learning/blob/69bce21ae8eda80ad6187534b2dce09cf6c59e17/trainers/maple.py#L111)

I hope it is clear now. 

Thank you and kind regards!

**Comment by Sandy-program** [comment]
Thank you very much for your help and look forward to your better work
