### ISSUE TITLE
How effective is the use of PromptSRC in Maple, and is it better than IVLP?

### ISSUE THREAD

**Issue by IHikari** [muzairkhattak/multimodal-prompt-learning#76]
Thank you for your excellent work. Could you please share how effective PromptSRC is in Maple and whether it is better than IVLP?Thank you for your time and help.

**Comment by muzairkhattak** [comment]
Hi @IHikari,

Thank you for showing interest in our work!

Regarding your query, we have unfortunately not experimented PromptSRC framework using MaPLe. However I suspect that it should perform well. 

The regularization losses in PromptSRC are helpful for all kind of models. 
I hope that is clear.

Thank you and kind regards!

**Comment by IHikari** [comment]
Thank you once again for your assistance and kind regards.
