### ISSUE TITLE
How to calculate the model's params，Learnable param?

### ISSUE THREAD

**Issue by IHikari** [muzairkhattak/multimodal-prompt-learning#80]
Dear author,could you share your method for calculating the total parameters, parameters, and FPS of MaPLe?

**Comment by muzairkhattak** [comment]
Hi @IHikari,

Thank you for showing interest in MaPLe! Sorry for the delayed response. 

For FPS, you can create a time counter around the inference code ([around these lines in the Dassl Library](https://github.com/KaiyangZhou/Dassl.pytorch/blob/c61a1b570ac6333bd50fb5ae06aea59002fb20bb/dassl/engine/trainer.py#L446)) and measure the time per batch.

For total parameters, you can use the starter code [as shown here.](https://github.com/KaiyangZhou/Dassl.pytorch/blob/c61a1b570ac6333bd50fb5ae06aea59002fb20bb/dassl/utils/torchtools.py#L242)

I hope that is helpful. Kind regards!

**Comment by IHikari** [comment]
thanks a lot
